media: static/projects
content:
  - name: homepage
    label: Main
    path: src/content/homepage.json
    type: file
    format: json
    fields:
      - { name: intro, label: Intro, type: string }
      - { name: email, label: Email, type: string }
      - name: footer
        label: Footer
        type: object
        list: true
        fields:
          - name: href
            label: URL
            type: string
          - name: text
            label: Text
            type: string
  - name: info
    label: Info Page
    path: src/content/info.json
    type: file
    format: json
    fields:
      - { name: bio, label: Bio, type: rich-text, options: { format: html, image: false } }
      - { name: tags, label: Tags, type: string, list: true }
  - name: project
    label: Projects
    type: collection
    path: src/content/projects
    filename: project-{fields.title}.json
    format: json
    subfolders: false
    view:
      fields: [ title, order ]
      primary: order
      sort: [ order ]
      default:
        sort: order
        order: asc
    fields:
      - { name: order, label: Order, type: number }
      - { name: title, label: Title, type: string }
      - { name: description, label: Description, type: string }
      - { name: image, label: Image, type: image, list: false, options: { input: static/projects, output: /projects } }
      - { name: year, label: Year, type: string }
      - { name: tags, label: Tags, type: string, list: true }
      - { name: credits, label: Credits, type: string }
      - { name: lede, label: Lede, type: rich-text, options: { format: html, image: false } }
      - name: blocks
        label: Content Blocks
        type: object
        list: true
        fields:
          - name: text
            label: Text
            type: object
            fields:
               - name: heading
                 label: Heading
                 type: string
               - name: text
                 label: Text
                 type: text
          - name: images
            label: Images
            type: object
            list: true
            fields:
               - name: image
                 label: Image
                 type: image
                 options: { input: static/projects, output: /projects }
               - name: caption
                 label: Caption
                 type: string
               - name: width
                 label: Width (%)
                 type: number
                 default: 100
               - name: marginLeft
                 label: Margin Left (%)
                 type: number
                 default: 0
                 
      
  - name: research
    label: Research
    type: collection
    path: src/content/research
    filename: research-{fields.title}.json
    format: json
    subfolders: false
    view:
      fields: [ title, order ]
      primary: order
      sort: [ order ]
      default:
        sort: order
        order: asc
    fields:
      - { name: order, label: Order, type: number }
      - { name: title, label: Title, type: string }
      - { name: description, label: Description, type: string }
      - { name: image, label: Image, type: image, list: false, options: { input: static/projects, output: /projects } }

