media: media
content:
  - name: projects
    label: Projects
    path: content/projects
    type: collection
    format: json
    view:
      fields: [title, published, date]
    fields:
      - name: published
        label: Published
        type: boolean
        default: true
      - name: title
        label: Title
        type: string
      - name: description
        label: Description
        type: string
      - name: image
        label: Image
        type: image
  - name: info
    label: Info page
    path: content/info.json
    type: file
    format: json
    fields:
      - name: bio
        label: Bio
        type: rich-text
        options: { format: html, image: false }
