media: static/projects
content:
  - name: info
    label: Info
    path: src/content/info.json
    type: file
    format: json
    fields:
      - { name: bio, label: Bio, type: rich-text, options: { format: html, image: false } }
      - { name: tags, label: Tags, type: string, list: true }
  - name: project
    label: Projects
    type: collection
    path: src/content/projects
    filename: project-{primary}.json
    format: json
    subfolders: false
    view:
      fields: [ order, line1, line2, line3 ]
      primary: order
      sort: [ order ]
      default:
        sort: order
        order: asc
    fields:
      - { name: order, label: Order, type: number }
      - { name: line1, label: First Line, type: string }
      - { name: line2, label: Second Line, type: string }
      - { name: line3, label: Third Line, type: string }
      - { name: src, label: Image, type: image, list: false, options: { input: static/projects, output: /projects, extensions: jpg, jpeg, png } }
